[package]
name = "gouda_input"
version = "0.1.0"
authors = ["Aengus McMillin <aengusmcmillin@gmail.com>"]
edition = "2018"

[dependencies]
enum-map = "*"
enum-map-derive = "*"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.8", features = ["xinput"] }