pub mod buffers2;
pub mod camera;
pub mod drawable;
pub mod font;
pub mod font_library;
pub mod model;
pub mod platform;
pub mod shader_lib;
pub mod shapes;
pub mod sprites;

#[cfg(target_os = "macos")]
pub use crate::platform::metal::buffers;
#[cfg(target_os = "macos")]
pub use crate::platform::metal::shader;
#[cfg(target_os = "macos")]
pub use crate::platform::metal::texture;
#[cfg(target_os = "macos")]
pub use crate::platform::metal::Renderer;
#[cfg(target_os = "macos")]
pub use crate::platform::metal::Scene;

#[cfg(target_os = "windows")]
pub use crate::platform::d3d11::buffers;
#[cfg(target_os = "windows")]
pub use crate::platform::d3d11::shader;
#[cfg(target_os = "windows")]
pub use crate::platform::d3d11::texture;
#[cfg(target_os = "windows")]
pub use crate::platform::d3d11::Renderer;
#[cfg(target_os = "windows")]
pub use crate::platform::d3d11::Scene;
