[package]
name = "gouda_images"
version = "0.0.0"
authors = ["Aengus McMillin <aengusmcmillin@gmail.com>"]
edition = "2018"

[dependencies]
png = "0.17.13"
compress = "0.2.1"
gouda_types = { path = "../gouda_types" }