[package]
name = "ogltutorialtest"
version = "0.1.0"
authors = ["Aengus McMillin <aengusmcmillin@gmail.com>"]
edition = "2018"

[dependencies]
gouda = { path = "../../" }
rand = "0.7.2"
cgmath = "0.18.0"
log = "0.4"
env_logger = "0.11.3"